project_name = "strudel-build"

[tasks]
build = "cargo build"
install = "cargo install --path ."
fmt = ["cargo clippy", "cargo +nightly fmt"]
check = "cargo +nightly fmt -- --check"
test = "cargo test --workspace --locked"
lint = "cargo clippy --workspace --all-targets --locked -- -D warnings"
mdlint = "rumdl check ."
ci = [":check", ":lint", ":mdlint", ":test"]
release = "./scripts/release.sh"

"example:hello-world" = "cargo run -- --config examples/HelloWorldApp/strudel.toml run"
"example:menu-bar" = "cargo run -- --config examples/MenuBarApp/strudel.toml run"
"example:multi-target" = "cargo run -- --config examples/MultiTargetApp/strudel.toml run"
"example:safari-extension" = "cargo run -- --config examples/SafariExtension/strudel.toml run"

"crates:publish" = {
  command = [
    "cargo publish -p strudel-appleid",
    "cargo publish -p strudel-dmg",
    "cargo publish -p strudel-icon",
    "cargo publish -p strudel-cli",
  ],
  env = {
    "CARGO_REGISTRY_TOKEN" = "axo://projects/crates-io/api-token",
  }
}

[global_packages]
rust = "stable"
"rvben/rumdl" = "^0.2.52"
