[package]
name = "strudel"
version = "0.4.0"
edition = "2024"
description = "Build and ship macOS/iOS apps without touching Xcode"
readme = "README.md"
homepage = "https://github.com/octavore/strudel"
repository = "https://github.com/octavore/strudel"
license = "Apache-2.0"
keywords = ["codesign", "dmg", "macos", "notarize", "swift"]
categories = ["command-line-utilities", "development-tools::build-utils"]

[workspace]
resolver = "2"
members = [".", "crates/dmg"]

[[bin]]
name = "strudel"
path = "src/main.rs"

[dependencies]
anstream = "1.0.0"
anyhow = "1"
base64 = "0.22"
clap = {version = "4", features = ["derive"]}
color-print = "0.3.7"
dmg = {path = "crates/dmg"}
indoc = "2"
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
plist = "1"
secrecy = "0.10.3"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
shellexpand = "3"
toml = "1.1"
ureq = {version = "3", features = ["json"]}
xdg = "3.0.0"

[dev-dependencies]
temp-env = "0.3"
tempfile = "3"

[profile.release]
strip = "symbols"
lto = "thin"
codegen-units = 1
