[package]
name = "strudel"
version = "0.1.0"
edition = "2024"
description = "Build and ship macOS/iOS apps without touching Xcode"
readme = "README.md"
homepage = "https://github.com/octavore/strudel"
repository = "https://github.com/octavore/strudel"
license = "Apache-2.0"
keywords = ["codesign", "dmg", "macos", "notarize", "swift"]
categories = ["command-line-utilities", "development-tools::build-utils"]

[[bin]]
name = "strudel"
path = "src/main.rs"

[dependencies]
anstream = "1.0.0"
anyhow = "1"
base64 = "0.22"
clap = {version = "4", features = ["derive"]}
color-print = "0.3.7"
indoc = "2"
plist = "1"
secrecy = "0.10.3"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
toml = "1.1"

[dev-dependencies]
temp-env = "0.3"
