name: Release

on:
  workflow_dispatch: # testing
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  release:
    name: release
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust (stable)
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup default stable
          rustup target add aarch64-apple-darwin

      - name: Cache cargo registry & target
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build (aarch64-apple-darwin)
        run: cargo build --release --target aarch64-apple-darwin --locked

      - name: Package
        id: package
        run: |
          ARCHIVE="strudel-${GITHUB_REF_NAME}-aarch64-apple-darwin.tar.gz"

          tar -czf "$ARCHIVE" -C target/aarch64-apple-darwin/release strudel

          echo "archive=$ARCHIVE" >> "$GITHUB_OUTPUT"

      # see homebrew.yml for updating the Homebrew formula on draft publish
      - name: Create draft release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ steps.package.outputs.archive }}
          generate_release_notes: true
          draft: true
          fail_on_unmatched_files: true
